version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: 52north/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
       ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - "zookeeper"
  postgis-debezium:
    image: 52north/postgis-debezium:1.0.0
    ports:
      - "5432:5432"
  connect:
    image: 52north/kafka-connect:0.10.2.0
    restart: unless-stopped
    ports:
      - "8083:8083"
    links:
      - "kafka:kafka"
      - "zookeeper:zookeeper"
      - "postgis-debezium:postgres"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      BOOTSTRAP_SERVERS: kafka:9092
