version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:0.5
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: debezium/kafka:0.5
    ports:
      - "9092:9092"
    environment:
       ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - "zookeeper"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
  postgis-debezium:
    image: 52north/postgis-debezium:1.0.0
    ports:
      - "5432:5432"
  connect:
    image: debezium/connect:0.5
    restart: unless-stopped
    ports:
      - "8083:8083"
    links:
      - "kafka:kafka"
      - "zookeeper:zookeeper"
      - "postgis-debezium:postgres"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my-connect-configs
      OFFSET_STORAGE_TOPIC: my-connect-offsets
      BOOTSTRAP_SERVERS: kafka:9092
      # ADVERTISED_HOST_NAME: localhost
      # BOOTSTRAP_SERVERS: kafka:9092
