version: '2'
services:
  connect:
    build: .
    image: 52north/debezium-connect:1.0.0
    container_name: debezium-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: localhost:9092
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
